version: "3"

services:
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db/0001-init.sh:/docker-entrypoint-initdb.d/0001-init.sh
      - ./db/0002-fill-staff.sh:/docker-entrypoint-initdb.d/0002-fill-staff.sh
      - ./db/full:/docker-entrypoint-initdb.d/
      #- ./pgData:/var/lib/psotgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"    
